manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config

  group-filter: [-optional]
  
  extensions:
      zephyr:
        modules:
          - path: modules/zmk-shield-corne-right-ssd1306
