manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: ssd1306
      path: modules/ssd1306
      revision: ""
      remote: none   

  self:
    path: config
